
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Projects</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    
  </head>
  <body>
    <?php include "header.php"; ?>
    
    <div class="container p-4">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.php">Projects</a></li>
                
            </ol>
        </nav>

        <?php if(isset($_SESSION["success"])): ?>
            <div class="alert alert-success" id="msg" role="alert">
                <?= $_SESSION["success"]; unset($_SESSION["success"]); ?>
            </div>
        <?php elseif(isset($_SESSION["error"])): ?>
            <div class="alert alert-danger" id="msg" role="alert">
                <?= $_SESSION["error"]; unset($_SESSION["error"]); ?>
            </div>
        <?php endif ?>

        <h1>Projects</h1>

        <?php include __DIR__ . "/addProject.phtml"; ?>
        
        <table class="table table-hover">
            <tr>    
                <th>Name</th>
                <th>Descrition</th>
                <th>Created at</th>
                <th>Detail</th>
            </tr>
            <?php foreach($projectsList as $project): ?>
            <tr>
                <td><?= $project->getName(); ?></td>
                <td><?= $project->getDescription(); ?></td>
                <td><?= $project->getCreatedAt(); ?></td>
                <td>
                    <a class="btn btn-primary" href="index.php?page=detail&projectId=<?= $project->getId(); ?>">Tasks
                        <span class="badge bg-white text-danger font-weight-bold"><?= $project->getCountTasks(); ?></span>
                    </a>
                </td>
            </tr>
            <?php endforeach ?>
        </table>
        
       
    </div>  

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
    <script src="main.js"></script>
    <script>
        setTimeout(function() {
        var msg = document.getElementById('msg');
        if (msg) {
            msg.style.display = 'none';
        }
    }, 2000);
    </script>
  </body>
</html>