<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <link rel="stylesheet" href="styles.css">
  </head>
  <body>
    <div class="container">
        
   
        <form action="index.php?page=auth" method="POST">
            <div class="row mb-3">
                <h1>Login</h1>
            </div>

            <div class="row mb-5">
                <?php if(isset($_SESSION["success"])): ?>
                    <div class="alert alert-success" id="msg" role="alert">
                        <?= $_SESSION["success"]; unset($_SESSION["success"]); ?>
                    </div>
                <?php elseif(isset($_SESSION["error"])): ?>
                    <div class="alert alert-danger" id="msg" role="alert">
                        <?= $_SESSION["error"]; unset($_SESSION["error"]); ?>
                    </div>
                <?php endif ?>
            </div>        
       
            <div class="row mb-4">
                <label for="username" class="col-sm-2 col-form-label">Username:</label>
                <div class="col-sm-10">
                <input type="text" class="form-control" id="username" name="username">
                </div>
            </div>

            <div class="row mb-4">
                <label for="password" class="col-sm-2 col-form-label">Password:</label>
                <div class="col-sm-10">
                <input type="password" class="form-control" id="password" name="password">
                </div>
            </div>

            <div class="row mb-4"></div>
                <button type="submit" class="btn btn-dark ">Sign in</button>
             </div>
        </form>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
    <script src="main.js"></script>
    <script>
        setTimeout(function() {
        var msg = document.getElementById('msg');
        if (msg) {
            msg.style.display = 'none';
        }
    }, 2000);
    </script>
  </body>
</html>